// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	io "io"
	reflect "reflect"
	time "time"

	gomock "github.com/golang/mock/gomock"
	models "github.com/wavlake/monorepo/internal/models"
)

// MockUserServiceInterface is a mock of UserServiceInterface interface.
type MockUserServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockUserServiceInterfaceMockRecorder
}

// MockUserServiceInterfaceMockRecorder is the mock recorder for MockUserServiceInterface.
type MockUserServiceInterfaceMockRecorder struct {
	mock *MockUserServiceInterface
}

// NewMockUserServiceInterface creates a new mock instance.
func NewMockUserServiceInterface(ctrl *gomock.Controller) *MockUserServiceInterface {
	mock := &MockUserServiceInterface{ctrl: ctrl}
	mock.recorder = &MockUserServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUserServiceInterface) EXPECT() *MockUserServiceInterfaceMockRecorder {
	return m.recorder
}

// GetFirebaseUIDByPubkey mocks base method.
func (m *MockUserServiceInterface) GetFirebaseUIDByPubkey(ctx context.Context, pubkey string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFirebaseUIDByPubkey", ctx, pubkey)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFirebaseUIDByPubkey indicates an expected call of GetFirebaseUIDByPubkey.
func (mr *MockUserServiceInterfaceMockRecorder) GetFirebaseUIDByPubkey(ctx, pubkey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFirebaseUIDByPubkey", reflect.TypeOf((*MockUserServiceInterface)(nil).GetFirebaseUIDByPubkey), ctx, pubkey)
}

// GetLinkedPubkeys mocks base method.
func (m *MockUserServiceInterface) GetLinkedPubkeys(ctx context.Context, firebaseUID string) ([]models.NostrAuth, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetLinkedPubkeys", ctx, firebaseUID)
	ret0, _ := ret[0].([]models.NostrAuth)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetLinkedPubkeys indicates an expected call of GetLinkedPubkeys.
func (mr *MockUserServiceInterfaceMockRecorder) GetLinkedPubkeys(ctx, firebaseUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetLinkedPubkeys", reflect.TypeOf((*MockUserServiceInterface)(nil).GetLinkedPubkeys), ctx, firebaseUID)
}

// GetUserEmail mocks base method.
func (m *MockUserServiceInterface) GetUserEmail(ctx context.Context, firebaseUID string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserEmail", ctx, firebaseUID)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserEmail indicates an expected call of GetUserEmail.
func (mr *MockUserServiceInterfaceMockRecorder) GetUserEmail(ctx, firebaseUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserEmail", reflect.TypeOf((*MockUserServiceInterface)(nil).GetUserEmail), ctx, firebaseUID)
}

// LinkPubkeyToUser mocks base method.
func (m *MockUserServiceInterface) LinkPubkeyToUser(ctx context.Context, pubkey, firebaseUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LinkPubkeyToUser", ctx, pubkey, firebaseUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// LinkPubkeyToUser indicates an expected call of LinkPubkeyToUser.
func (mr *MockUserServiceInterfaceMockRecorder) LinkPubkeyToUser(ctx, pubkey, firebaseUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LinkPubkeyToUser", reflect.TypeOf((*MockUserServiceInterface)(nil).LinkPubkeyToUser), ctx, pubkey, firebaseUID)
}

// UnlinkPubkeyFromUser mocks base method.
func (m *MockUserServiceInterface) UnlinkPubkeyFromUser(ctx context.Context, pubkey, firebaseUID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UnlinkPubkeyFromUser", ctx, pubkey, firebaseUID)
	ret0, _ := ret[0].(error)
	return ret0
}

// UnlinkPubkeyFromUser indicates an expected call of UnlinkPubkeyFromUser.
func (mr *MockUserServiceInterfaceMockRecorder) UnlinkPubkeyFromUser(ctx, pubkey, firebaseUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UnlinkPubkeyFromUser", reflect.TypeOf((*MockUserServiceInterface)(nil).UnlinkPubkeyFromUser), ctx, pubkey, firebaseUID)
}

// MockPostgresServiceInterface is a mock of PostgresServiceInterface interface.
type MockPostgresServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockPostgresServiceInterfaceMockRecorder
}

// MockPostgresServiceInterfaceMockRecorder is the mock recorder for MockPostgresServiceInterface.
type MockPostgresServiceInterfaceMockRecorder struct {
	mock *MockPostgresServiceInterface
}

// NewMockPostgresServiceInterface creates a new mock instance.
func NewMockPostgresServiceInterface(ctrl *gomock.Controller) *MockPostgresServiceInterface {
	mock := &MockPostgresServiceInterface{ctrl: ctrl}
	mock.recorder = &MockPostgresServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPostgresServiceInterface) EXPECT() *MockPostgresServiceInterfaceMockRecorder {
	return m.recorder
}

// GetTracksByAlbum mocks base method.
func (m *MockPostgresServiceInterface) GetTracksByAlbum(ctx context.Context, albumID string) ([]models.LegacyTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByAlbum", ctx, albumID)
	ret0, _ := ret[0].([]models.LegacyTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByAlbum indicates an expected call of GetTracksByAlbum.
func (mr *MockPostgresServiceInterfaceMockRecorder) GetTracksByAlbum(ctx, albumID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByAlbum", reflect.TypeOf((*MockPostgresServiceInterface)(nil).GetTracksByAlbum), ctx, albumID)
}

// GetTracksByArtist mocks base method.
func (m *MockPostgresServiceInterface) GetTracksByArtist(ctx context.Context, artistID string) ([]models.LegacyTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByArtist", ctx, artistID)
	ret0, _ := ret[0].([]models.LegacyTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByArtist indicates an expected call of GetTracksByArtist.
func (mr *MockPostgresServiceInterfaceMockRecorder) GetTracksByArtist(ctx, artistID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByArtist", reflect.TypeOf((*MockPostgresServiceInterface)(nil).GetTracksByArtist), ctx, artistID)
}

// GetUserAlbums mocks base method.
func (m *MockPostgresServiceInterface) GetUserAlbums(ctx context.Context, firebaseUID string) ([]models.LegacyAlbum, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserAlbums", ctx, firebaseUID)
	ret0, _ := ret[0].([]models.LegacyAlbum)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserAlbums indicates an expected call of GetUserAlbums.
func (mr *MockPostgresServiceInterfaceMockRecorder) GetUserAlbums(ctx, firebaseUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserAlbums", reflect.TypeOf((*MockPostgresServiceInterface)(nil).GetUserAlbums), ctx, firebaseUID)
}

// GetUserArtists mocks base method.
func (m *MockPostgresServiceInterface) GetUserArtists(ctx context.Context, firebaseUID string) ([]models.LegacyArtist, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserArtists", ctx, firebaseUID)
	ret0, _ := ret[0].([]models.LegacyArtist)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserArtists indicates an expected call of GetUserArtists.
func (mr *MockPostgresServiceInterfaceMockRecorder) GetUserArtists(ctx, firebaseUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserArtists", reflect.TypeOf((*MockPostgresServiceInterface)(nil).GetUserArtists), ctx, firebaseUID)
}

// GetUserByFirebaseUID mocks base method.
func (m *MockPostgresServiceInterface) GetUserByFirebaseUID(ctx context.Context, firebaseUID string) (*models.LegacyUser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserByFirebaseUID", ctx, firebaseUID)
	ret0, _ := ret[0].(*models.LegacyUser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserByFirebaseUID indicates an expected call of GetUserByFirebaseUID.
func (mr *MockPostgresServiceInterfaceMockRecorder) GetUserByFirebaseUID(ctx, firebaseUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserByFirebaseUID", reflect.TypeOf((*MockPostgresServiceInterface)(nil).GetUserByFirebaseUID), ctx, firebaseUID)
}

// GetUserTracks mocks base method.
func (m *MockPostgresServiceInterface) GetUserTracks(ctx context.Context, firebaseUID string) ([]models.LegacyTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserTracks", ctx, firebaseUID)
	ret0, _ := ret[0].([]models.LegacyTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserTracks indicates an expected call of GetUserTracks.
func (mr *MockPostgresServiceInterfaceMockRecorder) GetUserTracks(ctx, firebaseUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserTracks", reflect.TypeOf((*MockPostgresServiceInterface)(nil).GetUserTracks), ctx, firebaseUID)
}

// MockStorageServiceInterface is a mock of StorageServiceInterface interface.
type MockStorageServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockStorageServiceInterfaceMockRecorder
}

// MockStorageServiceInterfaceMockRecorder is the mock recorder for MockStorageServiceInterface.
type MockStorageServiceInterfaceMockRecorder struct {
	mock *MockStorageServiceInterface
}

// NewMockStorageServiceInterface creates a new mock instance.
func NewMockStorageServiceInterface(ctrl *gomock.Controller) *MockStorageServiceInterface {
	mock := &MockStorageServiceInterface{ctrl: ctrl}
	mock.recorder = &MockStorageServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorageServiceInterface) EXPECT() *MockStorageServiceInterfaceMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockStorageServiceInterface) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockStorageServiceInterfaceMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockStorageServiceInterface)(nil).Close))
}

// CopyObject mocks base method.
func (m *MockStorageServiceInterface) CopyObject(ctx context.Context, srcObject, dstObject string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyObject", ctx, srcObject, dstObject)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyObject indicates an expected call of CopyObject.
func (mr *MockStorageServiceInterfaceMockRecorder) CopyObject(ctx, srcObject, dstObject interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyObject", reflect.TypeOf((*MockStorageServiceInterface)(nil).CopyObject), ctx, srcObject, dstObject)
}

// DeleteObject mocks base method.
func (m *MockStorageServiceInterface) DeleteObject(ctx context.Context, objectName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteObject", ctx, objectName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteObject indicates an expected call of DeleteObject.
func (mr *MockStorageServiceInterfaceMockRecorder) DeleteObject(ctx, objectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteObject", reflect.TypeOf((*MockStorageServiceInterface)(nil).DeleteObject), ctx, objectName)
}

// GeneratePresignedURL mocks base method.
func (m *MockStorageServiceInterface) GeneratePresignedURL(ctx context.Context, objectName string, expiration time.Duration) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GeneratePresignedURL", ctx, objectName, expiration)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GeneratePresignedURL indicates an expected call of GeneratePresignedURL.
func (mr *MockStorageServiceInterfaceMockRecorder) GeneratePresignedURL(ctx, objectName, expiration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GeneratePresignedURL", reflect.TypeOf((*MockStorageServiceInterface)(nil).GeneratePresignedURL), ctx, objectName, expiration)
}

// GetBucketName mocks base method.
func (m *MockStorageServiceInterface) GetBucketName() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBucketName")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBucketName indicates an expected call of GetBucketName.
func (mr *MockStorageServiceInterfaceMockRecorder) GetBucketName() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBucketName", reflect.TypeOf((*MockStorageServiceInterface)(nil).GetBucketName))
}

// GetObjectMetadata mocks base method.
func (m *MockStorageServiceInterface) GetObjectMetadata(ctx context.Context, objectName string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectMetadata", ctx, objectName)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectMetadata indicates an expected call of GetObjectMetadata.
func (mr *MockStorageServiceInterfaceMockRecorder) GetObjectMetadata(ctx, objectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectMetadata", reflect.TypeOf((*MockStorageServiceInterface)(nil).GetObjectMetadata), ctx, objectName)
}

// GetObjectReader mocks base method.
func (m *MockStorageServiceInterface) GetObjectReader(ctx context.Context, objectName string) (io.ReadCloser, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetObjectReader", ctx, objectName)
	ret0, _ := ret[0].(io.ReadCloser)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetObjectReader indicates an expected call of GetObjectReader.
func (mr *MockStorageServiceInterfaceMockRecorder) GetObjectReader(ctx, objectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetObjectReader", reflect.TypeOf((*MockStorageServiceInterface)(nil).GetObjectReader), ctx, objectName)
}

// GetPublicURL mocks base method.
func (m *MockStorageServiceInterface) GetPublicURL(objectName string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPublicURL", objectName)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetPublicURL indicates an expected call of GetPublicURL.
func (mr *MockStorageServiceInterfaceMockRecorder) GetPublicURL(objectName interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPublicURL", reflect.TypeOf((*MockStorageServiceInterface)(nil).GetPublicURL), objectName)
}

// UploadObject mocks base method.
func (m *MockStorageServiceInterface) UploadObject(ctx context.Context, objectName string, data io.Reader, contentType string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UploadObject", ctx, objectName, data, contentType)
	ret0, _ := ret[0].(error)
	return ret0
}

// UploadObject indicates an expected call of UploadObject.
func (mr *MockStorageServiceInterfaceMockRecorder) UploadObject(ctx, objectName, data, contentType interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UploadObject", reflect.TypeOf((*MockStorageServiceInterface)(nil).UploadObject), ctx, objectName, data, contentType)
}

// MockNostrTrackServiceInterface is a mock of NostrTrackServiceInterface interface.
type MockNostrTrackServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockNostrTrackServiceInterfaceMockRecorder
}

// MockNostrTrackServiceInterfaceMockRecorder is the mock recorder for MockNostrTrackServiceInterface.
type MockNostrTrackServiceInterfaceMockRecorder struct {
	mock *MockNostrTrackServiceInterface
}

// NewMockNostrTrackServiceInterface creates a new mock instance.
func NewMockNostrTrackServiceInterface(ctrl *gomock.Controller) *MockNostrTrackServiceInterface {
	mock := &MockNostrTrackServiceInterface{ctrl: ctrl}
	mock.recorder = &MockNostrTrackServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNostrTrackServiceInterface) EXPECT() *MockNostrTrackServiceInterfaceMockRecorder {
	return m.recorder
}

// AddCompressionVersion mocks base method.
func (m *MockNostrTrackServiceInterface) AddCompressionVersion(ctx context.Context, trackID string, version models.CompressionVersion) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddCompressionVersion", ctx, trackID, version)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddCompressionVersion indicates an expected call of AddCompressionVersion.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) AddCompressionVersion(ctx, trackID, version interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddCompressionVersion", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).AddCompressionVersion), ctx, trackID, version)
}

// CreateTrack mocks base method.
func (m *MockNostrTrackServiceInterface) CreateTrack(ctx context.Context, pubkey, firebaseUID, extension string) (*models.NostrTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTrack", ctx, pubkey, firebaseUID, extension)
	ret0, _ := ret[0].(*models.NostrTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTrack indicates an expected call of CreateTrack.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) CreateTrack(ctx, pubkey, firebaseUID, extension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTrack", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).CreateTrack), ctx, pubkey, firebaseUID, extension)
}

// DeleteTrack mocks base method.
func (m *MockNostrTrackServiceInterface) DeleteTrack(ctx context.Context, trackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteTrack", ctx, trackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteTrack indicates an expected call of DeleteTrack.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) DeleteTrack(ctx, trackID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteTrack", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).DeleteTrack), ctx, trackID)
}

// GetTrack mocks base method.
func (m *MockNostrTrackServiceInterface) GetTrack(ctx context.Context, trackID string) (*models.NostrTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTrack", ctx, trackID)
	ret0, _ := ret[0].(*models.NostrTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTrack indicates an expected call of GetTrack.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) GetTrack(ctx, trackID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTrack", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).GetTrack), ctx, trackID)
}

// GetTracksByFirebaseUID mocks base method.
func (m *MockNostrTrackServiceInterface) GetTracksByFirebaseUID(ctx context.Context, firebaseUID string) ([]*models.NostrTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByFirebaseUID", ctx, firebaseUID)
	ret0, _ := ret[0].([]*models.NostrTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByFirebaseUID indicates an expected call of GetTracksByFirebaseUID.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) GetTracksByFirebaseUID(ctx, firebaseUID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByFirebaseUID", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).GetTracksByFirebaseUID), ctx, firebaseUID)
}

// GetTracksByPubkey mocks base method.
func (m *MockNostrTrackServiceInterface) GetTracksByPubkey(ctx context.Context, pubkey string) ([]*models.NostrTrack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTracksByPubkey", ctx, pubkey)
	ret0, _ := ret[0].([]*models.NostrTrack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTracksByPubkey indicates an expected call of GetTracksByPubkey.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) GetTracksByPubkey(ctx, pubkey interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTracksByPubkey", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).GetTracksByPubkey), ctx, pubkey)
}

// HardDeleteTrack mocks base method.
func (m *MockNostrTrackServiceInterface) HardDeleteTrack(ctx context.Context, trackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "HardDeleteTrack", ctx, trackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// HardDeleteTrack indicates an expected call of HardDeleteTrack.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) HardDeleteTrack(ctx, trackID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "HardDeleteTrack", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).HardDeleteTrack), ctx, trackID)
}

// MarkTrackAsCompressed mocks base method.
func (m *MockNostrTrackServiceInterface) MarkTrackAsCompressed(ctx context.Context, trackID, compressedURL string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTrackAsCompressed", ctx, trackID, compressedURL)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTrackAsCompressed indicates an expected call of MarkTrackAsCompressed.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) MarkTrackAsCompressed(ctx, trackID, compressedURL interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTrackAsCompressed", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).MarkTrackAsCompressed), ctx, trackID, compressedURL)
}

// MarkTrackAsProcessed mocks base method.
func (m *MockNostrTrackServiceInterface) MarkTrackAsProcessed(ctx context.Context, trackID string, size int64, duration int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MarkTrackAsProcessed", ctx, trackID, size, duration)
	ret0, _ := ret[0].(error)
	return ret0
}

// MarkTrackAsProcessed indicates an expected call of MarkTrackAsProcessed.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) MarkTrackAsProcessed(ctx, trackID, size, duration interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MarkTrackAsProcessed", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).MarkTrackAsProcessed), ctx, trackID, size, duration)
}

// SetPendingCompression mocks base method.
func (m *MockNostrTrackServiceInterface) SetPendingCompression(ctx context.Context, trackID string, pending bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetPendingCompression", ctx, trackID, pending)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetPendingCompression indicates an expected call of SetPendingCompression.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) SetPendingCompression(ctx, trackID, pending interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetPendingCompression", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).SetPendingCompression), ctx, trackID, pending)
}

// UpdateCompressionVisibility mocks base method.
func (m *MockNostrTrackServiceInterface) UpdateCompressionVisibility(ctx context.Context, trackID string, updates []models.VersionUpdate) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateCompressionVisibility", ctx, trackID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateCompressionVisibility indicates an expected call of UpdateCompressionVisibility.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) UpdateCompressionVisibility(ctx, trackID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateCompressionVisibility", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).UpdateCompressionVisibility), ctx, trackID, updates)
}

// UpdateTrack mocks base method.
func (m *MockNostrTrackServiceInterface) UpdateTrack(ctx context.Context, trackID string, updates map[string]interface{}) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTrack", ctx, trackID, updates)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTrack indicates an expected call of UpdateTrack.
func (mr *MockNostrTrackServiceInterfaceMockRecorder) UpdateTrack(ctx, trackID, updates interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTrack", reflect.TypeOf((*MockNostrTrackServiceInterface)(nil).UpdateTrack), ctx, trackID, updates)
}

// MockProcessingServiceInterface is a mock of ProcessingServiceInterface interface.
type MockProcessingServiceInterface struct {
	ctrl     *gomock.Controller
	recorder *MockProcessingServiceInterfaceMockRecorder
}

// MockProcessingServiceInterfaceMockRecorder is the mock recorder for MockProcessingServiceInterface.
type MockProcessingServiceInterfaceMockRecorder struct {
	mock *MockProcessingServiceInterface
}

// NewMockProcessingServiceInterface creates a new mock instance.
func NewMockProcessingServiceInterface(ctrl *gomock.Controller) *MockProcessingServiceInterface {
	mock := &MockProcessingServiceInterface{ctrl: ctrl}
	mock.recorder = &MockProcessingServiceInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockProcessingServiceInterface) EXPECT() *MockProcessingServiceInterfaceMockRecorder {
	return m.recorder
}

// ProcessCompression mocks base method.
func (m *MockProcessingServiceInterface) ProcessCompression(ctx context.Context, trackID string, option models.CompressionOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessCompression", ctx, trackID, option)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessCompression indicates an expected call of ProcessCompression.
func (mr *MockProcessingServiceInterfaceMockRecorder) ProcessCompression(ctx, trackID, option interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessCompression", reflect.TypeOf((*MockProcessingServiceInterface)(nil).ProcessCompression), ctx, trackID, option)
}

// ProcessCompressionAsync mocks base method.
func (m *MockProcessingServiceInterface) ProcessCompressionAsync(ctx context.Context, trackID string, option models.CompressionOption) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessCompressionAsync", ctx, trackID, option)
}

// ProcessCompressionAsync indicates an expected call of ProcessCompressionAsync.
func (mr *MockProcessingServiceInterfaceMockRecorder) ProcessCompressionAsync(ctx, trackID, option interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessCompressionAsync", reflect.TypeOf((*MockProcessingServiceInterface)(nil).ProcessCompressionAsync), ctx, trackID, option)
}

// ProcessTrack mocks base method.
func (m *MockProcessingServiceInterface) ProcessTrack(ctx context.Context, trackID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ProcessTrack", ctx, trackID)
	ret0, _ := ret[0].(error)
	return ret0
}

// ProcessTrack indicates an expected call of ProcessTrack.
func (mr *MockProcessingServiceInterfaceMockRecorder) ProcessTrack(ctx, trackID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTrack", reflect.TypeOf((*MockProcessingServiceInterface)(nil).ProcessTrack), ctx, trackID)
}

// ProcessTrackAsync mocks base method.
func (m *MockProcessingServiceInterface) ProcessTrackAsync(ctx context.Context, trackID string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ProcessTrackAsync", ctx, trackID)
}

// ProcessTrackAsync indicates an expected call of ProcessTrackAsync.
func (mr *MockProcessingServiceInterfaceMockRecorder) ProcessTrackAsync(ctx, trackID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ProcessTrackAsync", reflect.TypeOf((*MockProcessingServiceInterface)(nil).ProcessTrackAsync), ctx, trackID)
}

// RequestCompressionVersions mocks base method.
func (m *MockProcessingServiceInterface) RequestCompressionVersions(ctx context.Context, trackID string, compressionOptions []models.CompressionOption) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RequestCompressionVersions", ctx, trackID, compressionOptions)
	ret0, _ := ret[0].(error)
	return ret0
}

// RequestCompressionVersions indicates an expected call of RequestCompressionVersions.
func (mr *MockProcessingServiceInterfaceMockRecorder) RequestCompressionVersions(ctx, trackID, compressionOptions interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RequestCompressionVersions", reflect.TypeOf((*MockProcessingServiceInterface)(nil).RequestCompressionVersions), ctx, trackID, compressionOptions)
}

// MockAudioProcessorInterface is a mock of AudioProcessorInterface interface.
type MockAudioProcessorInterface struct {
	ctrl     *gomock.Controller
	recorder *MockAudioProcessorInterfaceMockRecorder
}

// MockAudioProcessorInterfaceMockRecorder is the mock recorder for MockAudioProcessorInterface.
type MockAudioProcessorInterfaceMockRecorder struct {
	mock *MockAudioProcessorInterface
}

// NewMockAudioProcessorInterface creates a new mock instance.
func NewMockAudioProcessorInterface(ctrl *gomock.Controller) *MockAudioProcessorInterface {
	mock := &MockAudioProcessorInterface{ctrl: ctrl}
	mock.recorder = &MockAudioProcessorInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockAudioProcessorInterface) EXPECT() *MockAudioProcessorInterfaceMockRecorder {
	return m.recorder
}

// IsFormatSupported mocks base method.
func (m *MockAudioProcessorInterface) IsFormatSupported(extension string) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "IsFormatSupported", extension)
	ret0, _ := ret[0].(bool)
	return ret0
}

// IsFormatSupported indicates an expected call of IsFormatSupported.
func (mr *MockAudioProcessorInterfaceMockRecorder) IsFormatSupported(extension interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IsFormatSupported", reflect.TypeOf((*MockAudioProcessorInterface)(nil).IsFormatSupported), extension)
}
