version: '3.8'

services:
  # Test Firebase Emulators
  firebase-emulators:
    image: node:18-alpine
    volumes:
      - .:/workspace
      - firebase_data:/workspace/.firebase
    working_dir: /workspace
    ports:
      - "9099:9099"  # Auth
      - "8080:8080"  # Firestore
      - "9199:9199"  # Storage
      - "4000:4000"  # Emulator Suite UI
    command: >
      sh -c "
        npm install -g firebase-tools &&
        firebase emulators:start --only auth,firestore,storage --project demo-project
      "
    environment:
      - FIREBASE_PROJECT_ID=demo-project
      - FIRESTORE_EMULATOR_HOST=localhost:8080
      - FIREBASE_AUTH_EMULATOR_HOST=localhost:9099
      - FIREBASE_STORAGE_EMULATOR_HOST=localhost:9199

  # Test Nostr Relay (nak)
  test-relay:
    image: golang:1.21-alpine
    volumes:
      - .:/workspace
    working_dir: /workspace/packages/dev-relay
    ports:
      - "7777:7777"
    command: >
      sh -c "
        go install github.com/fiatjaf/nak@latest &&
        nak serve --port 7777 --config relay-config.json
      "
    environment:
      - NAK_RELAY_NAME=wavlake-test-relay
      - NAK_RELAY_DESCRIPTION=Test relay for integration tests

  # Test Database (PostgreSQL for advanced testing scenarios)
  test-db:
    image: postgres:15-alpine
    environment:
      POSTGRES_DB: wavlake_test
      POSTGRES_USER: test_user
      POSTGRES_PASSWORD: test_pass
    ports:
      - "5433:5432"
    volumes:
      - test_db_data:/var/lib/postgresql/data
      - ./tools/scripts/test-db-init.sql:/docker-entrypoint-initdb.d/init.sql
    tmpfs:
      - /var/lib/postgresql/data  # Use tmpfs for faster tests

volumes:
  firebase_data:
  test_db_data: