# Frontend-specific tasks
version: '3'

vars:
  FRONTEND_DIR: .
  
tasks:
  install:
    desc: "Install frontend dependencies"
    cmds:
      - npm install

  dev:
    desc: "Start Vite development server"
    cmds:
      - npm run dev

  build:
    desc: "Build for production"
    cmds:
      - npm run build

  preview:
    desc: "Preview production build"
    cmds:
      - npm run preview

  test:
    desc: "Run all tests"
    cmds:
      - npm test

  test:watch:
    desc: "Run tests in watch mode"
    cmds:
      - npm run test:watch

  test:coverage:
    desc: "Run tests with coverage"
    cmds:
      - npm run test:coverage

  test:ui:
    desc: "Run tests with UI"
    cmds:
      - npm run test:ui

  test:e2e:
    desc: "Run end-to-end tests"
    cmds:
      - npm run test:e2e

  lint:
    desc: "Run ESLint"
    cmds:
      - npm run lint

  format:
    desc: "Format code with Prettier"
    cmds:
      - npm run format

  typecheck:
    desc: "Run TypeScript type checking"
    cmds:
      - npm run typecheck

  clean:
    desc: "Clean build artifacts and dependencies"
    cmds:
      - rm -rf dist node_modules .vite