// Generated by typegen at 2025-07-22T14:29:33-07:00
// DO NOT EDIT - This file is automatically generated

export interface User {
  id: string;
  email: string;
  displayName: string;
  profilePic: string;
  nostrPubkey: string;
}

export interface Track {
  id: string;
  title: string;
  artist: string;
  album?: string;
  duration: number;
  audioUrl: string;
  artworkUrl?: string;
  genre?: string;
  priceMsat?: number;
  ownerId: string;
  nostrEventId?: string;
}

