// Generated by typegen at 2025-07-23T09:08:59-07:00
// DO NOT EDIT - This file is automatically generated

export interface User {
  id: string;
  email: string;
  displayName: string;
  profilePic: string;
  nostrPubkey: string;
}

export interface Track {
  id: string;
  title: string;
  artist: string;
  album?: string;
  duration: number;
  audioUrl: string;
  artworkUrl?: string;
  genre?: string;
  priceMsat?: number;
  ownerId: string;
  nostrEventId?: string;
}

export interface APIUser {
  firebaseUID: string;
  activePubkeys: string[];
}

export interface NostrAuth {
  pubkey: string;
  firebaseUID: string;
  active: boolean;
  lastUsedAt: string;
  linkedAt: string;
}

export interface LinkedPubkeyInfo {
  pubkey: string;
  linked_at: string;
  last_used_at?: string;
}

export interface CompressionOption {
  bitrate: number;
  format: string;
  quality: string;
  sample_rate?: number;
}

export interface CompressionVersion {
  id: string;
  url: string;
  bitrate: number;
  format: string;
  quality: string;
  sample_rate: number;
  size: number;
  is_public: boolean;
  options: CompressionOption;
}

export interface NostrTrack {
  id: string;
  firebase_uid: string;
  pubkey: string;
  original_url: string;
  presigned_url?: string;
  extension: string;
  size?: number;
  duration?: number;
  is_processing: boolean;
  compression_versions?: CompressionVersion[];
  has_pending_compression: boolean;
  deleted: boolean;
  nostr_kind?: number;
  nostr_d_tag?: string;
  // Deprecated fields - kept for backward compatibility
  compressed_url?: string;
  is_compressed: boolean;
}

export interface VersionUpdate {
  version_id: string;
  is_public: boolean;
}

export interface LegacyUser {
  id: string;
  name: string;
  lightning_address: string;
  msat_balance: number;
  amp_msat: number;
  artwork_url: string;
  profile_url: string;
  is_locked: boolean;
}

export interface LegacyTrack {
  id: string;
  artist_id: string;
  album_id: string;
  title: string;
  order: number;
  play_count: number;
  msat_total: number;
  live_url: string;
  raw_url: string;
  size: number;
  duration: number;
  is_processing: boolean;
  is_draft: boolean;
  is_explicit: boolean;
  compressor_error: boolean;
  deleted: boolean;
  lyrics: string;
  published_at: string;
}

export interface LegacyArtist {
  id: string;
  user_id: string;
  name: string;
  artwork_url: string;
  artist_url: string;
  bio: string;
  twitter: string;
  instagram: string;
  youtube: string;
  website: string;
  npub: string;
  verified: boolean;
  deleted: boolean;
  msat_total: number;
}

export interface LegacyAlbum {
  id: string;
  artist_id: string;
  title: string;
  artwork_url: string;
  description: string;
  genre_id: number;
  subgenre_id: number;
  is_draft: boolean;
  is_single: boolean;
  deleted: boolean;
  msat_total: number;
  is_feed_published: boolean;
  published_at: string;
}

