// Generated by typegen at 2025-07-23T09:08:59-07:00
// DO NOT EDIT - This file is automatically generated

export interface LinkPubkeyRequest {
  pubkey?: string;
}

export interface UnlinkPubkeyRequest {
  pubkey: string;
}

export interface CheckPubkeyLinkRequest {
  pubkey: string;
}

export interface CreateTrackRequest {
  title: string;
  artist: string;
  album: string;
  duration: number;
  audioUrl: string;
  artworkUrl: string;
  genre: string;
  priceMsat: number;
}

export interface CreateNostrTrackRequest {
  extension: string;
}

