// Generated by typegen at 2025-07-22T14:29:33-07:00
// DO NOT EDIT - This file is automatically generated

export interface CreateTrackRequest {
  title: string;
  artist: string;
  album: string;
  duration: number;
  audioUrl: string;
  artworkUrl: string;
  genre: string;
  priceMsat: number;
}

