// Generated by typegen at 2025-07-22T14:29:33-07:00
// DO NOT EDIT - This file is automatically generated

export interface APIResponse {
  success: boolean;
  message?: string;
  data?: any;
  error?: string;
  timestamp: string;
}

export interface UserResponse {
  user: models.User | null;
}

export interface TracksResponse {
  tracks: models.Track[];
  total: number;
}

