// Generated by typegen at 2025-07-23T09:08:59-07:00
// DO NOT EDIT - This file is automatically generated

export interface LinkPubkeyResponse {
  success: boolean;
  message: string;
  firebase_uid: string;
  pubkey: string;
  linked_at: string;
}

export interface UnlinkPubkeyResponse {
  success: boolean;
  message: string;
  pubkey: string;
}

export interface GetLinkedPubkeysResponse {
  success: boolean;
  firebase_uid: string;
  linked_pubkeys: models.LinkedPubkeyInfo[];
}

export interface CheckPubkeyLinkResponse {
  success: boolean;
  is_linked: boolean;
  firebase_uid?: string;
  pubkey: string;
  email?: string;
}

export interface HeartbeatResponse {
  status: string;
  commit_sha: string;
}

export interface UserMetadataResponse {
  user: models.LegacyUser | null;
  artists: models.LegacyArtist[];
  albums: models.LegacyAlbum[];
  tracks: models.LegacyTrack[];
}

export interface APIResponse {
  success: boolean;
  message?: string;
  data?: any;
  error?: string;
  timestamp: string;
}

export interface UserResponse {
  user: models.User | null;
}

export interface TracksResponse {
  tracks: models.Track[];
  total: number;
}

export interface CreateTrackResponse {
  success: boolean;
  data?: models.NostrTrack | null;
  error?: string;
  message?: string;
}

export interface GetTracksResponse {
  success: boolean;
  data?: models.NostrTrack | null[];
  error?: string;
}

