name: Test Coverage

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: wavlake_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'
        
    - name: Install dependencies
      working-directory: ./apps/backend
      run: go mod download
      
    - name: Generate mocks
      working-directory: ./apps/backend
      run: go generate ./...
      
    - name: Run tests with coverage
      working-directory: ./apps/backend
      run: |
        go test -race -coverprofile=coverage.out -covermode=atomic ./internal/...
        
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./apps/backend/coverage.out
        flags: backend
        name: backend-coverage
        fail_ci_if_error: true